<?php

// SI ON VEUT FAIRE DE LA POO
// ON VA RANGER NOTRE CODE DANS UNE CLASSE ApiJson
// ON VA RANGER NOS CLASSES DANS DES FICHIERS
// CHAQUE CLASSE AURA SON FICHIER
// ATTENTION: CONVENTION DE NOMMAGE LE NOM COMMENCE PAR UNE MAJUSCULE
// ET ENSUITE ON EST EN CamelCase
// php/class/ApiJson.php
// AJOUTER UNE METHODE DANS LA CLASSE
// function traiterFormulaire ()

// COMMENT J'ACTIVE MA METHODE traiterFormulaire
// ETAPE1
// CHARGER LE CODE DE MA CLASSE
require_once "php/class/ApiJson.php";

// ETAPE2
// CREER UN OBJET POUR POUVOIR ACTIVER LA METHODE
$objet = new ApiJson;

// ETAPE3
// JE PASSE PAR L'OBJET POUR APPELER LA METHODE
// -> OPERATEUR D'ACCES
$objet -> traiterFormulaire();

